// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	model "kanggo/pkg/entity/model"

	mock "github.com/stretchr/testify/mock"
)

// UserUsecase is an autogenerated mock type for the UserUsecase type
type UserUsecase struct {
	mock.Mock
}

// GetByEmail provides a mock function with given fields: _a0, _a1
func (_m *UserUsecase) GetByEmail(_a0 context.Context, _a1 string) (*model.UserResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *model.UserResponse
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.UserResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: _a0, _a1
func (_m *UserUsecase) Insert(_a0 context.Context, _a1 model.RegisterRequest) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.RegisterRequest) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
