// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	schema "kanggo/pkg/entity/schema"

	mock "github.com/stretchr/testify/mock"
)

// UserStorage is an autogenerated mock type for the UserStorage type
type UserStorage struct {
	mock.Mock
}

// GetByEmail provides a mock function with given fields: ctx, email
func (_m *UserStorage) GetByEmail(ctx context.Context, email string) (*schema.User, error) {
	ret := _m.Called(ctx, email)

	var r0 *schema.User
	if rf, ok := ret.Get(0).(func(context.Context, string) *schema.User); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schema.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: ctx, data
func (_m *UserStorage) Insert(ctx context.Context, data schema.User) error {
	ret := _m.Called(ctx, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, schema.User) error); ok {
		r0 = rf(ctx, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
